travis:
  secure:
    BINSTAR_TOKEN: WhPY01xc7nqcK8CYveef1neIfn3CA2UI3a7xLou/C6amLoUuuufaJIC3CfxJ0MKAMN03SLLHg+nG6v11/nSy09iOQl0dxWPo1yOb0+wOE8xBUWIXsO4CwLjhaB63y2Z7we/jZVlBDXvYfDUZxnH/u/4A0XWW1QdTRyiW6yWEgATyaxhnevOuXpAHmjFdNqiCGdR1dUcu8YbVZtujaKhfVF+5RUnaD599ysek6rl+FGOu79vc4GiwvnplHJejgWKzA2cWoAMcXykI9F3i4NXFwGMuaK30rAclArLdOy3WrLdRO3w+D9vbEoId4SltpNioYhCLuo99b6NQa+O1wAu4fyOM7yln/IUUGfpK8Y9muThWknrGeJcSTQsqo0eo6qpSITsnbVTkVHLuLmffgxlxG7lN94T6qC3mSsxHZ4aOWZ13usJoO90hhhnlSoWuD0GrTPJ/zQkYejxGPX6Jw+UWkV+nP4fS6DP/voyPPE6t38pEa3adD9GmptQfqPq2xXjUHCMWR3RAUm99a6hw6UYbbczB88zIlgWCQ8d/TPTk7SgbG7EkwxFtXo/IG9oEz0RDTN0lyXIC8/32+jQqYX7fisnwfpQA068EKsWkax/LhLq5x1ta2LgcqqlO0qiWEpn3J7fsP3ao669kLCrD37L6n58aw4K8ew2wQawRaB6CSJ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
