travis:
  secure:
    BINSTAR_TOKEN: bQugxqMGzWKNDmJriix28odaobtYqTK3yQsS3WQCntSGJKBXmG8J5+Y3pGj1TjoQPKIWca9lcCSRpt9U2VGKTF/EniEMpVa6bT1hBaNknZVx29b8zPG8O55P+TFYJGLuh8mBHadenuVR2hs5D6YJPM1yR6BoH6znRlHKAvQzm33IebMIbIexNvotEKtaCVWrogxeJ2aqXazfJHbE0G1zPkP98HjwC635zhe5vwb4W4/aW0+2kYOCqxGrDnCsf02xr9y5U9+RvbSyx1LeqBYBv5q9MbRkVTRBSi1Itcwnsqv7V6P1shLvfLe1UxkGY6z2LJlIhPHLT9DrBjcLETJPhn7aT6TgqoMHAnjNs9UBCNJkgaQ55khI3jL1j8xGEw8xnULdjpddsSJyphrPSoOdBe4cTeJbw7Gnib+/IVP1hBKlySWDm8RZw0HEpAlS31Csi1haqE8oYtR1++3YQsV4Oy7Vl0lrcFNqPPSTZpAqukLI4r1xmErYxW1wHGEvhzFOes6vMt6Szi8CdF35vVUevvRM3WwtzD15+HgUB7kDy+za26Pwm6BGDri11tF8axu6+9qWW/DtDoaURKkdSgxWyvFf6pRCrgInr60S3zCIGOtsZtRWLMFYynPs43TKVH4t+XovIXTKWbKT09qLaq0H7cFj++Y/x+KrJVXqq1eIvvk=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
