travis:
  secure:
    BINSTAR_TOKEN: GNhhNZR5DnfJGqDvajUrNraDrQisaJj/U80svObaDD0JOVMzDEFrKmp+WKM0Gq1DI5pAzIOy92/ohretBLBKj6MSXTCyL0nsO0o1dcNsei7kRofleII3O/9BX9GNKWcRaRN0U4AhSevHB5qfJQbyDFql8WjECPFPO/v902pNVpj6AmpZemtFs3pXLLS5X2Py9mFLGsHRRzakAABd8sHp1C6ha7xQ/QLDiFoznl1E6VUFKkQRx78JeDchbPiI5DEKTuraMY/FVqGb3CVSHRKpEMcSI7CnfMwheuIk0UjOedXWRN0OxU1JeRny6v5+SCTv/Oi1h4w8qSpjSQKOBb1epwcxuuAcDJkPX3am774Cau5klv0NNQgpRdZ9SeceT42DNHF3g5rLRA0It1khOSSw2DI1VxTGlzYgXN3iiRpHYBzKv65YVl7bwhSk/NaZKKtiShl1Fn+RGDdduej4o3Q8svbt4UM3nFm7AjEjvcunvt/gsMncklN/d3YLkZn+N6mH+3X4aP3CosZMvp3nZvLqIR2GFDSmZKVJ0ErdlWVec0NYmL+SyYf4Yt/WF3/CeLUg86/FGVU7JE9379HTJenkyukFUSPrRZUuGcg5a5jOoRou+2Ljki2PIvbL4/ztWKIHgt38puUPELCC0UCp7u2FOuCqaMjNwaUk8goXlE5Wsaw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
